#! /usr/bin/env python

def main(): 
    
    #
    # Imports
    #
    import sys
    import os
    from fragplot import fragplotter, get_args

    args = get_args()
    
    plotter = fragplotter()
    plotter.run()

if __name__ == "__main__": main()