#! /usr/bin/env python

def main(): 
    
    #
    # Imports
    #
    import sys
    import os
    from fragplot import fragplotter
    
    help_message = """
    fragplot
    Python script to plot fragment sizes from two csv files (minIon and fragmentanalyzer).
    
    Usage:
        fragplot <fragment analyzer csv> <min ion csv>
    
    To run on the included Example data:
        fragplot example_data/electropherogram.csv example_data/minion.csv

    """
    
    try: assert len(sys.argv) == 3
    except AssertionError:
        print help_message
        sys.exit()
    
    plotter = fragplotter(sys.argv[1],sys.argv[2])
    plotter.run()

if __name__ == "__main__": main()